---

_You are currently looking at **version 1.2** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

# Assignment 2 - Pandas Introduction
All questions are weighted the same in this assignment.
## Part 1
The following code loads the olympics dataset (olympics.csv), which was derrived from the Wikipedia entry on [All Time Olympic Games Medals](https://en.wikipedia.org/wiki/All-time_Olympic_Games_medal_table), and does some basic data cleaning. 

The columns are organized as # of Summer games, Summer medals, # of Winter games, Winter medals, total # number of games, total # of medals. Use this dataset to answer the questions below.

In [19]:
import pandas as pd

df = pd.read_csv('olympics.csv', index_col=0, skiprows=1)

for col in df.columns:
    if col[:2]=='01':
        df.rename(columns={col:'Gold'+ col[4:]}, inplace=True)
    if col[:2]=='02':
        df.rename(columns={col:'Silver'+ col[4:]}, inplace=True)
    if col[:2]=='03':
        df.rename(columns={col:'Bronze'+ col[4:]}, inplace=True)
    if col[:1]=='№':
        df.rename(columns={col:'#'+col[1:]}, inplace=True)

names_ids = df.index.str.split('\s\(') # split the index by '('

df.index = names_ids.str[0] # the [0] element is the country name (new index) 
df['ID'] = names_ids.str[1].str[:3] # the [1] element is the abbreviation or ID (take first 3 characters from that)

df = df.drop('Totals')
df.head()
#df.columns

# Summer  Gold  Silver  Bronze  Total  # Winter  Gold.1  \
Afghanistan        13     0       0       2      2         0       0   
Algeria            12     5       2       8     15         3       0   
Argentina          23    18      24      28     70        18       0   
Armenia             5     1       2       9     12         6       0   
Australasia         2     3       4       5     12         0       0   

             Silver.1  Bronze.1  Total.1  # Games  Gold.2  Silver.2  Bronze.2  \
Afghanistan         0         0        0       13       0         0         2   
Algeria             0         0        0       15       5         2         8   
Argentina           0         0        0       41      18        24        28   
Armenia             0         0        0       11       1         2         9   
Australasia         0         0        0        2       3         4         5   

             Combined total   ID  
Afghanistan               2  AFG  
Algeria                  15  ALG  
Argentina                70  ARG  
Armenia                  12  ARM  
Australasia              12  ANZ

### Question 0 (Example)

What is the first country in df?

*This function should return a Series.*

In [2]:
# You should write your whole answer within the function provided. The autograder will call
# this function and compare the return value against the correct solution value
def answer_zero():
    # This function returns the row for Afghanistan, which is a Series object. The assignment
    # question description will tell you the general format the autograder is expecting
    return df.iloc[0]

# You can examine what your function returns by calling it in the cell. If you have questions
# about the assignment formats, check out the discussion forums for any FAQs
answer_zero() 

# Summer           13
Gold                0
Silver              0
Bronze              2
Total               2
# Winter            0
Gold.1              0
Silver.1            0
Bronze.1            0
Total.1             0
# Games            13
Gold.2              0
Silver.2            0
Bronze.2            2
Combined total      2
ID                AFG
Name: Afghanistan, dtype: object

### Question 1
Which country has won the most gold medals in summer games?

*This function should return a single string value.*

In [21]:
df.sort_values(by=['Gold'],ascending=False)

# Summer  Gold  Silver  Bronze  Total  # Winter  Gold.1  \
United States        26   976     757     666   2399        22      96   
Soviet Union          9   395     319     296   1010         9      78   
Great Britain        27   236     272     272    780        22      10   
France               27   202     223     246    671        22      31   
China                 9   201     146     126    473        10      12   
...                 ...   ...     ...     ...    ...       ...     ...   
Djibouti              7     0       0       1      1         0       0   
Cyprus                9     0       1       0      1        10       0   
Kyrgyzstan            5     0       1       2      3         6       0   
Senegal              13     0       1       0      1         5       0   
Afghanistan          13     0       0       2      2         0       0   

               Silver.1  Bronze.1  Total.1  # Games  Gold.2  Silver.2  \
United States       102        84      282       48    1072       859   
Soviet Union         57        59      194       18     473       376   
Great Britain         4        12       26       49     246       276   
France               31        47      109       49     233       254   
China                22        19       53       19     213       168   
...                 ...       ...      ...      ...     ...       ...   
Djibouti              0         0        0        7       0         0   
Cyprus                0         0        0       19       0         1   
Kyrgyzstan            0         0        0       11       0         1   
Senegal               0         0        0       18       0         1   
Afghanistan           0         0        0       13       0         0   

               Bronze.2  Combined total   ID  
United States       750            2681  USA  
Soviet Union        355            1204  URS  
Great Britain       284             806  GBR  
France              293             780  FRA  
China               145             526  CHN  
...                 ...             ...  ...  
Djibouti              1               1  DJI  
Cyprus                0               1  CYP  
Kyrgyzstan            2               3  KGZ  
Senegal               0               1  SEN  
Afghanistan           2               2  AFG  

[146 rows x 16 columns]

In [ ]:
df.loc[]

In [3]:
def answer_one():
    return df[df['Gold']==df['Gold'].max()].index[0]
answer_one()

'United States'

### Question 2
Which country had the biggest difference between their summer and winter gold medal counts?

*This function should return a single string value.*

In [4]:
def answer_two():
    return df[(df['Gold']-df['Gold.1']).abs()==(df['Gold']-df['Gold.1']).abs().max()].index[0]
answer_two()

'United States'

### Question 3
Which country has the biggest difference between their summer gold medal counts and winter gold medal counts relative to their total gold medal count? 

$$\frac{Summer~Gold - Winter~Gold}{Total~Gold}$$

Only include countries that have won at least 1 gold in both summer and winter.

*This function should return a single string value.*

In [5]:
def answer_three():
    acceptable = df[(df['Gold']>0) & (df['Gold.1']>0)]
    return ((acceptable['Gold']-acceptable['Gold.1'])/acceptable['Gold.2']).argmax()
answer_three()

4

### Question 4
Write a function that creates a Series called "Points" which is a weighted value where each gold medal (`Gold.2`) counts for 3 points, silver medals (`Silver.2`) for 2 points, and bronze medals (`Bronze.2`) for 1 point. The function should return only the column (a Series object) which you created, with the country names as indices.

*This function should return a Series named `Points` of length 146*

In [6]:
def answer_four():
    df['Points'] = 3*df['Gold.2']+2*df['Silver.2']+df['Bronze.2']
    return df['Points']
    #return df
answer_four()

Afghanistan                           2
Algeria                              27
Argentina                           130
Armenia                              16
Australasia                          22
                                   ... 
Yugoslavia                          171
Independent Olympic Participants      4
Zambia                                3
Zimbabwe                             18
Mixed team                           38
Name: Points, Length: 146, dtype: int64

## Part 2
For the next set of questions, we will be using census data from the [United States Census Bureau](http://www.census.gov). Counties are political and geographic subdivisions of states in the United States. This dataset contains population data for counties and states in the US from 2010 to 2015. [See this document](https://www2.census.gov/programs-surveys/popest/technical-documentation/file-layouts/2010-2015/co-est2015-alldata.pdf) for a description of the variable names.

The census dataset (census.csv) should be loaded as census_df. Answer questions using this as appropriate.

### Question 5
Which state has the most counties in it? (hint: consider the sumlevel key carefully! You'll need this for future questions too...)

*This function should return a single string value.*

In [7]:
census_df = pd.read_csv('census.csv')
census_df.head()

SUMLEV  REGION  DIVISION  STATE  COUNTY   STNAME         CTYNAME  \
0      40       3         6      1       0  Alabama         Alabama   
1      50       3         6      1       1  Alabama  Autauga County   
2      50       3         6      1       3  Alabama  Baldwin County   
3      50       3         6      1       5  Alabama  Barbour County   
4      50       3         6      1       7  Alabama     Bibb County   

   CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010  ...  RDOMESTICMIG2011  \
0        4779736            4780127          4785161  ...          0.002295   
1          54571              54571            54660  ...          7.242091   
2         182265             182265           183193  ...         14.832960   
3          27457              27457            27341  ...         -4.728132   
4          22915              22919            22861  ...         -5.527043   

   RDOMESTICMIG2012  RDOMESTICMIG2013  RDOMESTICMIG2014  RDOMESTICMIG2015  \
0         -0.193196          0.381066          0.582002         -0.467369   
1         -2.915927         -3.012349          2.265971         -2.530799   
2         17.647293         21.845705         19.243287         17.197872   
3         -2.500690         -7.056824         -3.904217        -10.543299   
4         -5.068871         -6.201001         -0.177537          0.177258   

   RNETMIG2011  RNETMIG2012  RNETMIG2013  RNETMIG2014  RNETMIG2015  
0     1.030015     0.826644     1.383282     1.724718     0.712594  
1     7.606016    -2.626146    -2.722002     2.592270    -2.187333  
2    15.844176    18.559627    22.727626    20.317142    18.293499  
3    -4.874741    -2.758113    -7.167664    -3.978583   -10.543299  
4    -5.088389    -4.363636    -5.403729     0.754533     1.107861  

[5 rows x 100 columns]

In [8]:
def answer_five():
    return census_df.groupby(['STNAME']).size().idxmax()
answer_five()

'Texas'

### Question 6
**Only looking at the three most populous counties for each state**, what are the three most populous states (in order of highest population to lowest population)? Use `CENSUS2010POP`.

*This function should return a list of string values.*

In [9]:
def answer_six():
    census = census_df[census_df['SUMLEV'] == 50] # Only district labels
    rearranged = census.sort_values(by=['STNAME','CENSUS2010POP'],ascending=False).groupby('STNAME').head(3)
    population = rearranged.groupby('STNAME').sum().sort_values(by='CENSUS2010POP', ascending=False).head(3).index.tolist()
    return population
answer_six()

['California', 'Texas', 'Illinois']

### Question 7
Which county has had the largest absolute change in population within the period 2010-2015? (Hint: population values are stored in columns POPESTIMATE2010 through POPESTIMATE2015, you need to consider all six columns.)

e.g. If County Population in the 5 year period is 100, 120, 80, 105, 100, 130, then its largest change in the period would be |130-80| = 50.

*This function should return a single string value.*

In [10]:
def answer_seven():
    census = census_df[census_df['SUMLEV'] == 50] # Only district labels
    
    # Don't want data from other columns while finding row max and min:
    pop_data = census[['STNAME','CTYNAME','POPESTIMATE2010','POPESTIMATE2011','POPESTIMATE2012','POPESTIMATE2013','POPESTIMATE2014','POPESTIMATE2015']]
    
    target_index = (pop_data.max(axis=1)-pop_data.min(axis=1)).argmax() # axis=1 to find max in row, not column
    # argmax() returns the index of the row with the max difference.
    return pop_data
    #return target_index
    #return pop_data.loc[target_index]['CTYNAME']
answer_seven()

STNAME            CTYNAME  POPESTIMATE2010  POPESTIMATE2011  \
1     Alabama     Autauga County            54660            55253   
2     Alabama     Baldwin County           183193           186659   
3     Alabama     Barbour County            27341            27226   
4     Alabama        Bibb County            22861            22733   
5     Alabama      Blount County            57373            57711   
...       ...                ...              ...              ...   
3188  Wyoming  Sweetwater County            43593            44041   
3189  Wyoming       Teton County            21297            21482   
3190  Wyoming       Uinta County            21102            20912   
3191  Wyoming    Washakie County             8545             8469   
3192  Wyoming      Weston County             7181             7114   

      POPESTIMATE2012  POPESTIMATE2013  POPESTIMATE2014  POPESTIMATE2015  
1               55175            55038            55290            55347  
2              190396           195126           199713           203709  
3               27159            26973            26815            26489  
4               22642            22512            22549            22583  
5               57776            57734            57658            57673  
...               ...              ...              ...              ...  
3188            45104            45162            44925            44626  
3189            21697            22347            22905            23125  
3190            20989            21022            20903            20822  
3191             8443             8443             8316             8328  
3192             7065             7160             7185             7234  

[3142 rows x 8 columns]

### Question 8
In this datafile, the United States is broken up into four regions using the "REGION" column. 

Create a query that finds the counties that belong to regions 1 or 2, whose name starts with 'Washington', and whose POPESTIMATE2015 was greater than their POPESTIMATE 2014.

*This function should return a 5x2 DataFrame with the columns = ['STNAME', 'CTYNAME'] and the same index ID as the census_df (sorted ascending by index).*

In [11]:
def answer_eight():
    only_reg = census_df[(census_df['REGION'] == 1) | (census_df['REGION'] == 2)]
    #return only_reg
    
    pop_great = only_reg[only_reg['POPESTIMATE2015'] > only_reg['POPESTIMATE2014']]
    #return pop_great
    
    only_wash = pop_great[pop_great['CTYNAME'].str.slice(stop=10) == "Washington"]
    #return only_wash
    
    display = only_wash[['STNAME','CTYNAME']].sort_index() # Only display required data in ascending order
    return display
answer_eight()

STNAME            CTYNAME
896           Iowa  Washington County
1419     Minnesota  Washington County
2345  Pennsylvania  Washington County
2355  Rhode Island  Washington County
3163     Wisconsin  Washington County